### ISSUE TITLE
[Image Classification] Failed to execute 'dispatch' on 'MLContext': Invalid inputs

### ISSUE THREAD

**Issue by ibelem** [microsoft/webnn-developer-preview#46]
Failed to execute 'dispatch' on 'MLContext' after landing https://github.com/microsoft/webnn-developer-preview/pull/45

### Repro Steps A
1. Enable WebNN in browser
2. Visit https://microsoft.github.io/webnn-developer-preview/demos/image-classification/?provider=webnn&devicetype=gpu&model=mobilenet-v2&run=1
3. Click "Classify" button
4. It will show performance results, click "Classify" button again

### Repro Steps B
1. Enable WebNN in browser
2. Visit https://microsoft.github.io/webnn-developer-preview/demos/image-classification/?provider=webnn&devicetype=gpu&model=mobilenet-v2&run=1
3. Click "Classify" button
4. It will show performance results, click "ResNet50" button
5. Click "Classify" button

### Actual Result

Failed to execute 'dispatch' on 'MLContext': Invalid inputs: The context of MLGraph doesn't match the context of the MLTensor with name "pixel_values".

![Image](https://github.com/user-attachments/assets/5c23e410-fa2f-421e-8806-4be4774ab32b)

@egalli do you have any clue to fix this issue, thanks!

CC @Honry @fdwr @huningxin

### Note

This issue didn't occur by using compute() in ORT Web before.

#### How to build the Transformers.js dists and apply for developer preview image classification demo

1. Clone https://github.com/xenova/transformers.js/tree/v3 // "onnxruntime-web": "1.20.0-dev.20241016-2b8fc5529b",
2. `npm install`
3. Apply the patch https://github.com/ibelem/transformers.js/blob/v3-webnn-2/0001-v3-perf-code.patch or follow the code change in https://github.com/ibelem/transformers.js/commit/7cb760f43a6b5e9c616e755b159dd57ab118d05d
4. `npm run build`
5. Copy the dists from `/transformers.js/dist` to `webnn-developer-preview/assets/dist_transformers/dynamic-runs-1.19-dev/`

**Comment by egalli** [comment]
It seems to be related to how we created a new `MLContext` per sessions. I have created a [PR](https://github.com/microsoft/onnxruntime/pull/22510) that adds a cache for `MLContext`s so that `InferencesSession`s created with the same parameters will use the same `MLContext`.

FYI, while testing change to the ORT, I noticed that [transformers.js defaults to downloading the .wasm file from a CDN](https://github.com/huggingface/transformers.js/blob/7a58d6e11968dd85dc87ce37b2ab37213165889a/src/backends/onnx.js#L187). If we want to use the version this repo, we'll need to set that variable to
```js
transformers.env.backends.onnx.wasm.wasmPaths = "../../assets/dist_transformers/dynamic-runs-1.20-dev/";
```

**Comment by ibelem** [comment]
Thank you @egalli , I will re-build transformers.js dist once merging the https://github.com/microsoft/onnxruntime/pull/22510 , also set transformers.env.backends.onnx.wasm.wasmPaths.

**Comment by fdwr** [comment]
> Thank you [@egalli](https://github.com/egalli) , I will re-build transformers.js dist once merging the [microsoft/onnxruntime#22510](https://github.com/microsoft/onnxruntime/pull/22510) , also set transformers.env.backends.onnx.wasm.wasmPaths.

@ibelem - Tis merged.

**Comment by ibelem** [comment]
The https://github.com/microsoft/onnxruntime/pull/22556 caused demos regression, will wait for the fix landed in new ORT dev dists then fix this bug.

**Comment by fdwr** [comment]
> Hold the dists update since the [microsoft/onnxruntime#22278](https://github.com/microsoft/onnxruntime/pull/22278) and [microsoft/onnxruntime#22556](https://github.com/microsoft/onnxruntime/pull/22556) cause demos regression.

Merged `Revert "[WebNN] Fallback the node when its output doesn't have shape info" https://github.com/microsoft/onnxruntime/pull/22669`.

**Comment by ibelem** [comment]
@fdwr 

We need to wait for PRs below to be merged and integrated into the new development version of ORT distributions, otherwise more models may fail to run.

- https://github.com/microsoft/onnxruntime/pull/22701 Fix issues with MLTensor caching

**Comment by ibelem** [comment]
https://github.com/microsoft/onnxruntime/pull/22701 Fix issues with MLTensor caching was landed, waiting for next dev version of ONNX ORT dist later than 1.21.0-dev.20241106 @https://www.npmjs.com/package/onnxruntime-web?activeTab=versions .
