### ISSUE TITLE
Trying image classification demo twice yields error - Failed to execute 'dispatch' on 'MLContext': Invalid inputs: The context of MLGraph doesn't match the context of the MLTensor with name "pixel_values".

### ISSUE THREAD

**Issue by fdwr** [microsoft/webnn-developer-preview#51]
- Go to https://microsoft.github.io/webnn-developer-preview/demos/image-classification/?provider=webnn&devicetype=gpu&model=resnet-50&run=5 via either:
  - Microsoft Edge	130.0.2849.52 (Official build) (64-bit) 
    Revision	0fc97f382530af0427e50f1116a5baaa0c89f90d
    Chromium version	130.0.6723.59
  - Google Chrome	132.0.6817.0 (Official Build) canary (64-bit)
- Click `Classify` once.
- Click `Classify` again.
- See error: `Failed to execute 'dispatch' on 'MLContext': Invalid inputs: The context of MLGraph doesn't match the context of the MLTensor with name "pixel_values".`

![Image](https://github.com/user-attachments/assets/27875bd9-321d-4f92-ae69-9459460500ce)

@ibelem

**Comment by ibelem** [comment]
A duplicate of https://github.com/microsoft/webnn-developer-preview/issues/46

**Comment by fdwr** [comment]
Duplicate.
