### ISSUE TITLE
MLTensorUsage is not defined in Classification and Whisper

### ISSUE THREAD

**Issue by fdwr** [microsoft/webnn-developer-preview#57]
Google Chrome 133.0.6835.0 (Official Build) canary (64-bit)

Probably from: webnn: Remove grace-period support for MLTensorUsage | https://chromium-review.googlesource.com/c/chromium/src/+/6015318

FYI @a-sully and @ibelem.

![Image](https://github.com/user-attachments/assets/b37e8bd8-cf1e-4614-be9d-74bc4db4005f)

![Image](https://github.com/user-attachments/assets/a470172b-3b00-49f2-92df-d24fd713b463)

**Comment by ibelem** [comment]
@fdwr Yes, we discussed this issue at midnight yesterday. Will try to use ort test dists as possible to fix these demos at first.

**Comment by fdwr** [comment]
Relevant: https://github.com/microsoft/onnxruntime/pull/22831

**Comment by huningxin** [comment]
A workaround, once the models loaded, open the developer console, paste and run the following polyfill code

```js
if (typeof MLTensorUsage == 'undefined') window.MLTensorUsage = {WEBGPU_INTEROP: 1, READ: 2, WRITE: 4}
```

**Comment by ibelem** [comment]
#58

1.21.0-dev.20241112-cdc8db9984 | 8 days ago

Still waiting for dev dist > 20241112 to deploy.
